### ISSUE TITLE
Not all template items created

### ISSUE THREAD

**Issue by khammo01** [figueiredorui/1-click-child-links#25] opened 2018-04-25 21:50 UTC
Out of 9 User Story templates, only some are created under a Feature. In limited testing the number created varies, as few as 2 and as many as 6.

**Comment by pabrams** [comment] 2018-07-05 21:46
Sounds like validation errors that aren't being shown.

**Comment by rprouse** [comment] 2019-02-14 16:26
This is likely a duplicate of #22

**Closed** 2020-06-07 08:45 UTC
